### ISSUE TITLE
Env vars not converted using str(), per se

### ISSUE THREAD

**Issue by scopatz** [ninjaaron/xonsh-quickstart#1]
In the environment variables section, you say,

> In subprocess mode, their values will have str() called on them when they are converted into arguments

Actually, what happens is slightly more involved.  First the environment is checked to see if a to-string conversion function is registered for that variable. Then, if it isn't `str()` is called.  This is how we can get custom behavior for variables that are boolean valued, are lists, are ints, etc.

**Comment by scopatz** [comment]
This is also an issue in the Python substitutions section.  The variable that you are using just hasn't been registered, so it falls back to the default behavior

**Comment by ninjaaron** [comment]
Thanks so much, @scopatz, for having a look and giving feedback! (and thanks for creating xonsh!) I'm not able to detect any of the "custom behaviors" you mention for lists, booleans, etc.

Here is a paste from my terminal:

```sh
~> $foo = 'foo bar baz'.split()
~> echo $foo
['foo', 'bar', 'baz']
~> ls $foo
/usr/bin/ls: cannot access '['\''foo'\'', '\''bar'\'', '\''baz'\'']': No such file or directory
~> $bar = True
~> echo $bar
True
~> ls $bar
/usr/bin/ls: cannot access 'True': No such file or directory
~> 
```

It looks to me very much like the above list and boolean are simply being converted to strings before they are passed to the executable. What am I missing? Is there something I need to do to trigger special behaviors?

**Comment by ninjaaron** [comment]
Ah! I see what you mean. I misinterpreted what you said to mean that various _types_ were registered for different sorts of conversion, but I understand now that you mean _variables_. Funny how you meant what you said and not what I thought.

I'll amend the document immediately. Thanks again for the feedback.

**Comment by scopatz** [comment]
Haha yeah, custom conversions are registered with *variables*, not *types* :)  We need to have a better public interface for registering new variable converters with the enviornment, but there is something there right now
